---


- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: Install PostgrSQL and required packages
  apt: name={{item}}
  with_items:
     - postgresql
     - postgresql-contrib
     - python-software-properties
     - software-properties-common
     - libpq-dev
     - python-psycopg2
